'use client'
import { useEffect, useMemo, useState } from 'react'

type Category={id:string;name:string;slug:string}; type Account={id:string;username:string;displayName:string;bio:string|null;profileImageUrl:string|null;profileUrl:string;verified:boolean;categories:{category:Category}[]}

export default function Home(){
 const [accounts,setAccounts]=useState<Account[]>([]),[categories,setCategories]=useState<Category[]>([]),[q,setQ]=useState(''),[cat,setCat]=useState(''),[sort,setSort]=useState('recent'),[open,setOpen]=useState(false),[userId,setUserId]=useState('demo-user'),[username,setUsername]=useState(''),[categoryId,setCategoryId]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);const r=await fetch(`/api/accounts?q=${encodeURIComponent(q)}&category=${encodeURIComponent(cat)}`);if(r.ok)setAccounts(await r.json());setLoading(false)}
 useEffect(()=>{fetch('/api/categories').then(r=>r.json()).then(setCategories);},[]); useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q,cat])
 const visible=useMemo(()=>[...accounts].sort((a,b)=>sort==='name'?a.displayName.localeCompare(b.displayName):sort==='handle'?a.username.localeCompare(b.username):0),[accounts,sort])
 async function submit(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,categoryId,userId})});const data=await r.json();if(!r.ok){setError(data.error||'Could not add account');return}setOpen(false);setUsername('');await load()}
 return <main className="shell"><header className="topbar"><div className="brand"><span className="logo">𝕏</span><span>X Follow</span></div><button className="add" onClick={()=>setOpen(true)}>＋ Add account</button></header>
 <section className="hero"><div className="eyebrow">Curated X directory</div><h1>Find people worth following.</h1><p>Discover interesting X accounts by category. Browse experts, builders, creators and voices — then follow them directly on X.</p></section>
 <section className="toolbar"><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people, handles or bios…"/><select className="select" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Newest</option><option value="name">Name A–Z</option><option value="handle">Handle A–Z</option></select></section>
 <nav className="chips"><button className={`chip ${!cat?'active':''}`} onClick={()=>setCat('')}>All</button>{categories.map(c=><button key={c.id} className={`chip ${cat===c.slug?'active':''}`} onClick={()=>setCat(c.slug)}>{c.name}</button>)}</nav>
 {loading?<div className="empty">Loading accounts…</div>:visible.length?<div className="grid">{visible.map(a=><article className="card" key={a.id}><div className="person"><img className="avatar" src={a.profileImageUrl||`https://ui-avatars.com/api/?name=${encodeURIComponent(a.displayName)}&background=1d9bf0&color=fff`} alt=""/><div><div className="name">{a.displayName}{a.verified?' ✓':''}</div><div className="handle">@{a.username}</div></div></div><p className="bio">{a.bio||'No bio available.'}</p><div>{a.categories.map(x=><span className="tag" key={x.category.id}>{x.category.name}</span>)}</div><a className="follow" href={a.profileUrl} target="_blank" rel="noreferrer">Follow on X ↗</a></article>)}</div>:<div className="empty">No accounts found. Try another search or category.</div>}
 {open&&<div className="modalBack" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="modal"><h2>Add an X account</h2><p>Enter a public X handle and choose the category where it should appear.</p><form className="form" onSubmit={submit}><input required value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username"/><select required value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required value={userId} onChange={e=>setUserId(e.target.value)} placeholder="Your user ID"/><small>For production, replace this with your authentication session.</small>{error&&<div className="error">{error}</div>}<div className="actions"><button type="button" className="cancel" onClick={()=>setOpen(false)}>Cancel</button><button className="submit">Add account</button></div></form></div></div>}</main>
}
